version: "2.0"
services:
  zones:
    build: ./zones/src/main/docker/
    ports:
      - "8081:8080"
    links:
        - mongodb:db
        - discovery:eureka
  playlists:
    build: ./Playlists/src/main/docker/
    ports:
      - "8080:8080"
    links:
      - mongodb:db
      - discovery:eureka
  synchro:
    build: ./Synchro/src/main/docker/
    ports:
      - "8090:8080"
    links:
      - mongodb:db
      - discovery:eureka  
  discovery:
    build: ./eureka-service/src/main/docker/
    ports:
      - "8761:8761"
  mongodb:
    image: mongo
    ports:
      - "27017"